/*
MIT License
Copyright (c) 2026 Ronan Le Meillat - SCTG Development
Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:
The above copyright notice and this permission notice shall be included in all
copies or substantial portions of the Software.
THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/

/** Types the `env` object provided by `cloudflare:test` with the Worker bindings. */

import type { D1Migration } from "cloudflare:test";
import type { Env as WorkerEnv } from "../src/env.js";
import type * as ServerEntrypoint from "../src/index.js";

declare global {
  namespace Cloudflare {
    interface Env extends WorkerEnv {
      /** Injected by vitest.config.ts (miniflare bindings). */
      TEST_MIGRATIONS: D1Migration[];
    }

    /**
     * Normally generated by `wrangler types`; declared by hand since this project doesn't run
     * that step. Points `cloudflare:workers`'s `exports` (used in place of the deprecated
     * `cloudflare:test` `SELF`) at this Worker's actual default export.
     */
    interface GlobalProps {
      mainModule: typeof ServerEntrypoint;
    }
  }
}
